apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-euoo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-mtct-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-euoo@sha256:94bb6fe161ddb269d8c1c15203a9cebd0cc431870299b9ac8d08e8ba4135f257
        name: my-python
        resources: {}
status: {}
