apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-euoo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-euoo
    app.kubernetes.io/part-of: mc-unsupported-runtime
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-euoo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-euoo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-euoo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-mtct-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-euoo@sha256:94bb6fe161ddb269d8c1c15203a9cebd0cc431870299b9ac8d08e8ba4135f257
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
